import { parseColorToHSL } from '../utils/colorConversion';
import { formatDuration } from '../utils/format';
import type { ValidationIssue, ValidationReport } from './validateTypes';

/**
 * Rendering the colour validation report.
 *
 * Split from the command file, which held registration, the run, the report
 * and the accessibility checks in one 485-line file.
 */

/**
 * Generate validation report
 */
export function generateValidationReport(
	report: ValidationReport,
	durationMs: number,
): string {
	const lines: string[] = [];

	// Header
	lines.push('# Color Validation Report');
	lines.push('');
	lines.push(`**Generated**: ${new Date().toISOString()}`);
	lines.push(`**Validation Time**: ${formatDuration(durationMs)}`);
	lines.push('');

	// Summary
	lines.push('## Summary');
	lines.push('');
	lines.push(`- **Total Colors**: ${report.summary.total}`);
	lines.push(`- **Valid**: ${report.summary.valid}`);
	lines.push(`- **Invalid**: ${report.summary.invalid}`);
	lines.push(`- **Errors**: ${report.summary.errors}`);
	lines.push(`- **Warnings**: ${report.summary.warnings}`);
	lines.push(
		`- **Success Rate**: ${((report.summary.valid / report.summary.total) * 100).toFixed(1)}%`,
	);
	lines.push('');

	// Validation Options
	lines.push('## Validation Options');
	lines.push('');
	if (report.options.checkFormat)
		lines.push('- **Format Validation**: Enabled');
	if (report.options.checkAccessibility)
		lines.push('- **Accessibility Validation**: Enabled');
	if (report.options.checkContrast) {
		lines.push('- **Contrast Validation**: Enabled');
		if (report.options.contrastBackground) {
			lines.push(`  - Background: \`${report.options.contrastBackground}\``);
		}
		if (report.options.minContrastAA) {
			lines.push(`  - WCAG AA: ${report.options.minContrastAA}:1`);
		}
		if (report.options.minContrastAAA) {
			lines.push(`  - WCAG AAA: ${report.options.minContrastAAA}:1`);
		}
	}
	if (report.options.allowedFormats) {
		lines.push(
			`- **Allowed Formats**: ${report.options.allowedFormats
				.map((f) => f.toUpperCase())
				.join(', ')}`,
		);
	}
	lines.push('');

	// Issues by Type
	const issuesByType = new Map<string, ValidationIssue[]>();
	for (const result of report.colors) {
		for (const issue of result.issues) {
			const key = `${issue.type}-${issue.severity}`;
			if (!issuesByType.has(key)) {
				issuesByType.set(key, []);
			}
			const issues = issuesByType.get(key);
			if (issues) {
				issues.push(issue);
			}
		}
	}

	if (issuesByType.size > 0) {
		lines.push('## Issues by Type');
		lines.push('');
		lines.push('| Type | Severity | Count |');
		lines.push('|------|----------|-------|');

		for (const [key, issues] of Array.from(issuesByType.entries()).sort()) {
			const [type, severity] = key.split('-');
			const icon =
				severity === 'error' ? '🔴' : severity === 'warning' ? '🟡' : '🔵';
			lines.push(`| ${icon} ${type} | ${severity} | ${issues.length} |`);
		}
		lines.push('');
	}

	// Detailed Results
	const invalidColors = report.colors.filter(
		(r) => !r.valid || r.issues.length > 0,
	);
	if (invalidColors.length > 0) {
		lines.push('## Detailed Results');
		lines.push('');

		for (const result of invalidColors) {
			const statusIcon = result.valid ? '🟡' : '🔴';
			lines.push(`### ${statusIcon} \`${result.color.value}\``);
			lines.push('');

			if (result.contrastRatio !== undefined) {
				lines.push(`**Contrast Ratio**: ${result.contrastRatio.toFixed(2)}:1`);
			}
			if (result.accessibilityLevel) {
				lines.push(`**Accessibility Level**: ${result.accessibilityLevel}`);
			}
			lines.push('');

			if (result.issues.length > 0) {
				lines.push('**Issues**:');
				for (const issue of result.issues) {
					const issueIcon =
						issue.severity === 'error'
							? '🔴'
							: issue.severity === 'warning'
								? '🟡'
								: '🔵';
					lines.push(`- ${issueIcon} ${issue.message}`);
				}
				lines.push('');
			}

			if (result.suggestions.length > 0) {
				lines.push('**Suggestions**:');
				for (const suggestion of result.suggestions) {
					lines.push(`- 💡 ${suggestion}`);
				}
				lines.push('');
			}
		}
	}

	// Valid Colors Summary
	const validColors = report.colors.filter(
		(r) => r.valid && r.issues.length === 0,
	);
	if (validColors.length > 0) {
		lines.push('## Valid Colors');
		lines.push('');
		lines.push(
			`✅ **${validColors.length} colors passed all validation checks**`,
		);
		lines.push('');
	}

	lines.push('---');
	lines.push('*Generated by Colors-LE Color Validation*');

	return lines.join('\n');
}

// Helper functions

export function checkAccessibilityIssues(color: string): ValidationIssue[] {
	const issues: ValidationIssue[] = [];

	// Check for very light colors that might be hard to see
	const hsl = parseColorToHSL(color);
	if (hsl) {
		if (hsl.l > 95) {
			issues.push({
				type: 'accessibility',
				severity: 'warning',
				message: 'Very light color may be difficult to see',
				suggestion: 'Consider using a darker shade for better visibility',
			});
		}

		if (hsl.l < 5) {
			issues.push({
				type: 'accessibility',
				severity: 'warning',
				message: 'Very dark color may be difficult to see',
				suggestion: 'Consider using a lighter shade for better visibility',
			});
		}

		if (hsl.s < 5 && hsl.l > 40 && hsl.l < 60) {
			issues.push({
				type: 'accessibility',
				severity: 'info',
				message: 'Low saturation color may appear gray to some users',
				suggestion:
					'Consider increasing saturation for better color distinction',
			});
		}
	}

	return issues;
}

export function checkColorBlindnessIssues(color: string): ValidationIssue[] {
	const issues: ValidationIssue[] = [];

	// Simplified color blindness checks
	const hsl = parseColorToHSL(color);
	if (hsl) {
		// Red-green color blindness issues
		if ((hsl.h >= 0 && hsl.h <= 30) || (hsl.h >= 330 && hsl.h <= 360)) {
			if (hsl.s > 50) {
				issues.push({
					type: 'accessibility',
					severity: 'info',
					message:
						'Red colors may be problematic for users with red-green color blindness',
					suggestion:
						'Consider using additional visual cues (patterns, shapes) alongside color',
				});
			}
		}

		if (hsl.h >= 90 && hsl.h <= 150 && hsl.s > 50) {
			issues.push({
				type: 'accessibility',
				severity: 'info',
				message:
					'Green colors may be problematic for users with red-green color blindness',
				suggestion:
					'Consider using additional visual cues (patterns, shapes) alongside color',
			});
		}
	}

	return issues;
}
